### PR TITLE
Clarify GitHub hosting & pull requests.

### PR DESCRIPTION
**Pull request by rduplain**
Link directly to the repository URL and provide a help link instead of a link placeholder.

-Ron

### CODE REVIEW

**Comment by seanherron** [comment]
I was mid-pushing up a commit that fixed this as well - +1 to getting this merged!

**Comment by nayanjain** [comment]
I added the PR link, if you get latest I can merge these changes.

**Comment by rduplain** [comment]
I would stick with the pull-request help link that I have in my pull request. If someone has used GitHub, all they need is the repo URL. If not, the help article is the place to be.

**Comment by nayanjain** [comment]
In that case please pull latest and apply your changes.

Sent from my Verizon Wireless 4G LTE DROID

Ron DuPlain notifications@github.com wrote:

I would stick with the pull-request help link that I have in my pull request. If someone has used GitHub, all they need is the repo URL. If not, the help article is the place to be.

**Comment by rduplain** [comment]
Updated, ready to pull.

**Pull request merged**
